version: "3"
services:
  vote:
    build:
      context: ./vote
    image: lamia2023/vote:v2
  result:
    build:
      context: ./result
    image: lamia2023/result:v2
  worker:
    build:
      context: ./worker
    image: lamia2023/worker:v2
  seed:
    build:
      context: ./seed-data
    image: lamia2023/seed:v2